### ISSUE TITLE
Cancellation

### ISSUE THREAD

**Issue by jakub-trzebiatowski** [Maia-Everett/jpromises#1]
Can promises be cancelled? If not, is there any reasonable way to implement this on top of the public API?

**Comment by Maia-Everett** [comment]
Promises in the JPromises library have no standard cancel API by design.

How would it work if it was possible? The promise handler is a black box that could have opened any number of resources (files, network connections, database connections, etc.) by the time it needs to be cancelled. All the promise knows is that eventually, some thread, possibly and even probably outside of its control, will call `resolve` or `reject`.

The closest thing you can do is designate a special exception as a cancellation exception and call `reject` with it. Obviously it will not immediately interrupt any application code started by the promise handler (it is the responsibility of the application to do so if it desires), but it will ensure that any future attempts to call `resolve` or `reject` fail with `IllegalStateException`.<sup>1</sup>

This is, in fact, what Java 8 `CompletableFuture` does. Its authors made an unfortunate decision to extend `Future`, which meant they had to implement `cancel`. All it does is reject the `CompletableFuture` with a `CancellationException` without interrupting any running application code. In fact, unlike a standard `Future`, it ignores the `mayInterruptIfRunning` flag.

There is a way to emulate this behavior with JPromises, but it's ugly.

```java
class PromiseCancel {
	private PromiseFactory promiseFactory = ...;
	private Consumer<Throwable> reject;

	void startPromise() {
		promiseFactory.promise(resolve -> {
			reject = resolve::reject;
			... // promise resolution logic
		}).onException(e -> {
			if (e instanceof CancellationException) {
				// handle cancel
			} else {
				// handle any other exception
			}
		});
	}

	void cancelPromise() {
		reject.accept(new CancellationException());
	}
}
````

In the next version, I'll add some syntactic sugar to handle a specific exception by class, so the `onException` part can at least be rewritten as

```java
onException(CancellationException.class, e -> {
	// handle cancel
})
```

________________
<sup>1</sup> Actually, *should* they? When I designed it that way, it seemed to me that trying to resolve or reject a promise more than once is a bug in application code. But both JavaScript promises and `CompletableFuture` just silently refuse to change state more than once. And of course `JsPromise` doesn't throw `IllegalStateException` because the underlying JavaScript promise doesn't. Something to consider. This may be reason enough to change the behavior in 0.4.
